"""init

Revision ID: 50d45b971a38
Revises: 
Create Date: 2026-06-25 16:12:32.904550

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '50d45b971a38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
